export const ERROR_CODES = {
    BAD_REQUEST: 'ERR_BAD_REQUEST',
    UNAUTHORIZED: 'ERR_UNAUTHORIZED',
    FORBIDDEN: 'ERR_FORBIDDEN',
    NOT_FOUND: 'ERR_NOT_FOUND',
    CONFLICT: 'ERR_CONFLICT',
    SERVER_ERROR: 'ERR_SERVER_ERROR',

    USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'ERR_USER_ALREADY_EXISTS',
    INVALID_PASSWORD: 'ERR_INVALID_PASSWORD',
    TOKEN_GENERATION_FAILED: 'ERR_TOKEN_GENERATION_FAILED',
    PASSWORD_ENCRYPTION_FAILED: 'ERR_PASSWORD_ENCRYPTION_FAILED',
    MISSING_FIELD: "ERR_MISSING_FIELD",

};